"use client";

import { ArrowLeft, Calendar, CheckCircle2, ChevronRight, CircleEllipsis, Clock3, FileText, FolderOpen, ListChecks, MoreHorizontal, Plus, Send, Sparkles, Target } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { Project } from "@/lib/demo-data";
import { Shell } from "./shell";
import { DriveLink, RiskBadge, StatusDot } from "./ui";

const tabs = ["Overview", "Tasks", "Documents", "Notes"];

export function ProjectDetail({ project }: { project: Project }) {
  const [tab, setTab] = useState("Overview");
  const [done, setDone] = useState(project.tasks.map(task => !!task.done));
  const completed = done.filter(Boolean).length;
  return <Shell><section className="page detail-page"><Link className="back-link" href="/projects"><ArrowLeft size={16}/>All applications</Link><div className="project-header"><div className="project-title-line"><span className={`project-symbol accent-${project.accent}`}>{project.university.charAt(0)}</span><div><p className="eyebrow">{project.country} · {project.stage}</p><h1>{project.university}</h1><p className="subtle">{project.title}</p></div></div><div className="header-buttons"><DriveLink href={project.driveUrl}/><button className="icon-button"><MoreHorizontal size={20}/></button></div></div>
  <div className="detail-meta"><span><Calendar size={16}/>{project.deadline}</span><span><Clock3 size={16}/><strong>{project.daysLeft} days remaining</strong></span><RiskBadge risk={project.risk}/><span className="stage-chip">{project.stage}</span></div>
  <div className="detail-tabs">{tabs.map(t => <button onClick={() => setTab(t)} key={t} className={tab === t ? "active" : ""}>{t}</button>)}</div>
  {tab === "Overview" ? <div className="detail-layout"><div className="detail-main"><section className="next-action-card"><span className="next-icon"><Sparkles size={20}/></span><div><p className="eyebrow">Ziggy’s next best move</p><h2>{project.nextAction}</h2><p>{project.risk === "high" ? "This unlocks your most time-sensitive work. You’ve got this." : "A meaningful next step, sized to keep your momentum going."}</p></div><button className="button dark">Start now <ChevronRight size={16}/></button></section>
    <section className="detail-section"><div className="section-heading"><div><p className="eyebrow">Progress with purpose</p><h2>Application readiness</h2></div><strong className="readiness-number">{project.readiness}% ready</strong></div><div className="readiness-panel"><div className="ring" style={{"--progress": `${project.readiness * 3.6}deg`} as React.CSSProperties}><span>{project.readiness}<small>%</small></span></div><div><p>{project.requirementsDone} of {project.requirementsTotal} requirements ready</p><div className="requirement-mini">{project.requirements.slice(0,5).map(req => <span className={req.status === "Final" ? "complete" : req.status === "Waiting" ? "waiting" : "incomplete"} key={req.name}>{req.status === "Final" ? "✓" : req.status === "Waiting" ? "◌" : "·"} {req.name}</span>)}</div><button className="text-button">Review all requirements <ChevronRight size={15}/></button></div></div></section>
    <section className="detail-section"><div className="section-heading"><div><p className="eyebrow">Make progress visible</p><h2>Next tasks</h2></div><button className="text-button"><Plus size={15}/>Add task</button></div><div className="detail-task-list">{project.tasks.map((task, i) => <button className="detail-task" onClick={() => setDone(items => items.map((item, index) => index === i ? !item : item))} key={task.title}><StatusDot done={done[i]}/><div><strong className={done[i] ? "task-done" : ""}>{task.title}</strong><span>{task.estimate} · Due {task.due}</span></div><span className={`priority ${task.priority.toLowerCase()}`}>{task.priority}</span></button>)}</div><p className="task-progress">{completed} of {project.tasks.length} shown tasks complete</p></section>
    <section className="detail-section"><div className="section-heading"><div><p className="eyebrow">Your checklist</p><h2>Required documents</h2></div><button className="text-button">Open folder <FolderOpen size={15}/></button></div><div className="requirements-list">{project.requirements.map(req => <div className="requirement" key={req.name}><StatusDot done={req.status === "Final"}/><span>{req.name}{req.critical && <em>required</em>}</span><small className={req.status.toLowerCase().replaceAll(" ", "-")}>{req.status}</small></div>)}</div></section>
  </div><aside className="detail-side"><section className="side-card deadline-card"><p className="eyebrow">Countdown</p><strong>{project.daysLeft}<small> days</small></strong><p>until the official deadline</p><div className="deadline-meter"><i style={{width: `${Math.min(100, (60-project.daysLeft)/60*100)}%`}}/></div><span>Personal target: {project.milestones.at(-2)?.date ?? project.deadline}</span></section><section className="side-card"><div className="side-title"><span><Calendar size={17}/>Milestones</span><button><Plus size={15}/></button></div><div className="milestone-list">{project.milestones.map(m => <div key={m.title}><StatusDot done={m.done}/><span>{m.title}<small>{m.date}</small></span></div>)}</div></section><section className="side-card"><div className="side-title"><span><FileText size={17}/>Recent files</span></div><div className="file-list">{project.documents.map(doc => <a href={project.driveUrl} target="_blank" rel="noreferrer" key={doc.name}><span className="file-icon"><FileText size={15}/></span><span>{doc.name}<small>{doc.status} · {doc.updated}</small></span></a>)}</div></section></aside></div> : <div className="tab-placeholder"><span><ListChecks size={28}/></span><h2>{tab} view is taking shape</h2><p>This polished MVP keeps the live overview front and centre. Your {tab.toLowerCase()} are already represented in it.</p></div>}
  </section></Shell>;
}
